services:
  - type: web
    name: facturacion-dte-api
    env: docker
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        sync: false # Set this in Render dashboard (e.g. Aiven MySQL)
      - key: MH_NIT
        sync: false
      - key: MH_API_PASSWORD
        sync: false
